<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240618104458 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE agent_fournisseur (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, raisonsocial LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, adresseadministratif LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, prenom LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, tel LONGTEXT NOT NULL, tel2 LONGTEXT NOT NULL, fax LONGTEXT NOT NULL, email LONGTEXT NOT NULL, website LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE avoir_clients (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, modepaimement LONGTEXT NOT NULL, numerocompte LONGTEXT NOT NULL, codeclient LONGTEXT NOT NULL, codefacture LONGTEXT NOT NULL, montanttotalfacture LONGTEXT NOT NULL, montantsaisie LONGTEXT NOT NULL, montantrestant LONGTEXT NOT NULL, datemontant LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE avoir_clients_history (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, modepaimement LONGTEXT NOT NULL, numerocompte LONGTEXT NOT NULL, codeclient LONGTEXT NOT NULL, codefacture LONGTEXT NOT NULL, montanttotalfacture LONGTEXT NOT NULL, montantsaisie LONGTEXT NOT NULL, ancienmontant LONGTEXT NOT NULL, payetawa LONGTEXT NOT NULL, restantmazal LONGTEXT NOT NULL, datemontant LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE avoir_fournisseurs (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeavoir LONGTEXT NOT NULL, codefournisseur LONGTEXT NOT NULL, codefacture LONGTEXT NOT NULL, montantrestant LONGTEXT NOT NULL, datemontant LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commande_client (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clientel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commande_fournisseur (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, monlogo LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, nomclient LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, telclient LONGTEXT NOT NULL, datedevis LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commande_fournisseur_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, monlogo LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, nomclient LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, telclient LONGTEXT NOT NULL, datedevis LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE conge (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, codeemployee LONGTEXT NOT NULL, datedebut LONGTEXT NOT NULL, datefin LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrat_client (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, fichier LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrat_fournisseur (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, fichier LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devis (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devis_fournisseur_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devis_fournisseurs (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, monlogo LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, nomclient LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, telclient LONGTEXT NOT NULL, datedevis LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE deviserp_ligne_devis_fournisseurs_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_absence (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, codeemployee LONGTEXT NOT NULL, datedebut LONGTEXT NOT NULL, datefin LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_admin (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, prenom LONGTEXT NOT NULL, email LONGTEXT NOT NULL, motdepasse LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_bon_de_reception_fournisseur (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_bon_livraison_client_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_catalogue (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, fichier LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_categorie_premiere (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_chauffeurs (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, prenom LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, tel LONGTEXT NOT NULL, tel2 LONGTEXT NOT NULL, email LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_client (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, anciencode LONGTEXT NOT NULL, typearrive LONGTEXT NOT NULL, surnom LONGTEXT NOT NULL, prenomdeux LONGTEXT NOT NULL, pays LONGTEXT NOT NULL, ville LONGTEXT NOT NULL, codepostal LONGTEXT NOT NULL, raisonsocial LONGTEXT NOT NULL, registrecommerce LONGTEXT NOT NULL, matriculefiscal LONGTEXT NOT NULL, rib LONGTEXT NOT NULL, intervenanttype LONGTEXT NOT NULL, intervenantnom LONGTEXT NOT NULL, cin LONGTEXT NOT NULL, cheque LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, prenom LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, tel LONGTEXT NOT NULL, tel2 LONGTEXT NOT NULL, fax LONGTEXT NOT NULL, email LONGTEXT NOT NULL, website LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_commande_client (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, monlogo LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, nomclient LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, telclient LONGTEXT NOT NULL, codedevis LONGTEXT NOT NULL, datedevis LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_consomation_parc (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codevehicule LONGTEXT NOT NULL, nombrelitre DOUBLE PRECISION NOT NULL, prix DOUBLE PRECISION NOT NULL, datesaisie DATE NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_contact (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nomsociete LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, adresseadminstratif LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, prenom LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, tel LONGTEXT NOT NULL, tel2 LONGTEXT NOT NULL, fax LONGTEXT NOT NULL, email LONGTEXT NOT NULL, website LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_contact_categorie (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_contrat_vehicule (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, typecontrat LONGTEXT NOT NULL, datedebut DATE NOT NULL, datefin DATE NOT NULL, montant LONGTEXT NOT NULL, fichierjoint LONGTEXT NOT NULL, idvehicule LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_devis_client_new_from_factures (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, modepaimement LONGTEXT NOT NULL, numbercompte LONGTEXT NOT NULL, montantsaisie LONGTEXT NOT NULL, accomptesaisie LONGTEXT NOT NULL, etatfacture LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_devis_fournisseurs_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_document (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, fichier LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_ecriture_comptable (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, compte LONGTEXT NOT NULL, libelle LONGTEXT NOT NULL, montant LONGTEXT NOT NULL, idlibelle LONGTEXT NOT NULL, debit LONGTEXT NOT NULL, credit LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_employe (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, prenom LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, tel LONGTEXT NOT NULL, tel2 LONGTEXT NOT NULL, fax LONGTEXT NOT NULL, email LONGTEXT NOT NULL, website LONGTEXT NOT NULL, image LONGTEXT NOT NULL, login LONGTEXT NOT NULL, motdepasse LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_equipe (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_event (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_factures_client (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, monlogo LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, nomclient LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, telclient LONGTEXT NOT NULL, codedevis LONGTEXT NOT NULL, datedevis LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_factures_client_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, champ_demande_new LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, modepaimement LONGTEXT NOT NULL, numbercompte LONGTEXT NOT NULL, montantsaisie LONGTEXT NOT NULL, accomptesaisie LONGTEXT NOT NULL, etatfacture LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_factures_fournisseur_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_factures_fournisseurs_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_feuille_de_temps (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, codeemployee LONGTEXT NOT NULL, datedebut LONGTEXT NOT NULL, datefin LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_formation (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_fournisseur (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codefournisseur LONGTEXT NOT NULL, raisonsocial LONGTEXT NOT NULL, ville LONGTEXT NOT NULL, pays LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, prenom LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, tel LONGTEXT NOT NULL, tel2 LONGTEXT NOT NULL, fax LONGTEXT NOT NULL, email LONGTEXT NOT NULL, website LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_heure_supp (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, codeemployee LONGTEXT NOT NULL, datedebut LONGTEXT NOT NULL, datefin LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation LONGTEXT NOT NULL, datemodification LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_intervenant_categorie (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_ligne_devis_fournisseurs_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_ligne_factures_client (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_ligne_factures_fournisseurs (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_ligne_production (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeligne LONGTEXT NOT NULL, refproduit LONGTEXT NOT NULL, ancienqte LONGTEXT NOT NULL, newqte LONGTEXT NOT NULL, sortie LONGTEXT NOT NULL, restant LONGTEXT NOT NULL, dateligne LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_location_parc (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, typecontrat LONGTEXT NOT NULL, datedebut DATE NOT NULL, datefin DATE NOT NULL, montant LONGTEXT NOT NULL, fichierjoint LONGTEXT NOT NULL, idvehicule LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_matiere_premiere (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeproduit LONGTEXT NOT NULL, image LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, type LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, methodeapprovisionement LONGTEXT NOT NULL, puvht LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, puvttc LONGTEXT NOT NULL, remisemax LONGTEXT NOT NULL, unitestock LONGTEXT NOT NULL, fournisseur LONGTEXT NOT NULL, dateachat DATE NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_message (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, idenvoie LONGTEXT NOT NULL, idreception LONGTEXT NOT NULL, titre LONGTEXT NOT NULL, texte LONGTEXT NOT NULL, fichier LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_modele_vehicule (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_mouvement_stock (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeproduit LONGTEXT NOT NULL, ancienqte LONGTEXT NOT NULL, newquantitetonne LONGTEXT NOT NULL, newquantitequnto LONGTEXT NOT NULL, newquantitekilo LONGTEXT NOT NULL, newvalue LONGTEXT NOT NULL, date LONGTEXT NOT NULL, type LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation LONGTEXT NOT NULL, datemodification LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_note_de_frais (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, codeemployee LONGTEXT NOT NULL, datedebut LONGTEXT NOT NULL, datefin LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_notifications (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, texte LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_objectifs (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, assignea LONGTEXT NOT NULL, equipe LONGTEXT NOT NULL, typeprogramme LONGTEXT NOT NULL, datedebut DATE NOT NULL, datefin DATE NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_parametres (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, logosociete LONGTEXT NOT NULL, nomsociete LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, codepostal LONGTEXT NOT NULL, ville LONGTEXT NOT NULL, tel LONGTEXT NOT NULL, tel2 LONGTEXT NOT NULL, fax LONGTEXT NOT NULL, registrecommerce LONGTEXT NOT NULL, matriculefiscale LONGTEXT NOT NULL, rib LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_pays (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_pistes (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, prenom LONGTEXT NOT NULL, societe LONGTEXT NOT NULL, secteur LONGTEXT NOT NULL, mobile LONGTEXT NOT NULL, email LONGTEXT NOT NULL, website LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, codepostal LONGTEXT NOT NULL, pays LONGTEXT NOT NULL, image LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_produit (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeproduit LONGTEXT NOT NULL, image LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, type LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, methodeapprovisionement LONGTEXT NOT NULL, puvht LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, puvttc LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, unitestock LONGTEXT NOT NULL, fournisseur LONGTEXT NOT NULL, dateachat DATE NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_produit_compose (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeproduit LONGTEXT NOT NULL, image LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, type LONGTEXT NOT NULL, categorie LONGTEXT NOT NULL, methodeapprovisionement LONGTEXT NOT NULL, prixachatht LONGTEXT NOT NULL, prixventeht LONGTEXT NOT NULL, unitestock LONGTEXT NOT NULL, fournisseur LONGTEXT NOT NULL, dateachat DATE NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_projet (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, datedebut DATE NOT NULL, datefin DATE NOT NULL, fichier LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_releve_bancaire (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, solde LONGTEXT NOT NULL, datesolde LONGTEXT NOT NULL, fichierreleve LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_tache (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, description LONGTEXT NOT NULL, idprojet LONGTEXT NOT NULL, datedebut DATE NOT NULL, datefin DATE NOT NULL, fichier LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_type_matiere_premiere (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_vehicule (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, image LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, matricule LONGTEXT NOT NULL, modele LONGTEXT NOT NULL, dateachat DATE NOT NULL, datemiseensirculation DATE NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE erp_ville (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture_autres_new_data (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nomclient LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, telclient LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, type LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, typepaiment LONGTEXT NOT NULL, numerocheque LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture_client_new_data (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture_fournisseur_new_data (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, monfax LONGTEXT NOT NULL, monregistre LONGTEXT NOT NULL, monmatricule LONGTEXT NOT NULL, clientcode LONGTEXT NOT NULL, clientraison LONGTEXT NOT NULL, clientnom LONGTEXT NOT NULL, clientprenom LONGTEXT NOT NULL, clienttel LONGTEXT NOT NULL, clientfax LONGTEXT NOT NULL, clientadresse LONGTEXT NOT NULL, clientmatricule LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, remises LONGTEXT NOT NULL, timbres LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, chauffeurnom LONGTEXT NOT NULL, chauffeurvehicule LONGTEXT NOT NULL, creationcode LONGTEXT NOT NULL, creationnom LONGTEXT NOT NULL, creationprenom LONGTEXT NOT NULL, creationdate LONGTEXT NOT NULL, creationheure LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE factures_clients (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codefacture LONGTEXT NOT NULL, monlogo LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, nomclient LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, datedevis LONGTEXT NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE factures_fournisseurs (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, monlogo LONGTEXT NOT NULL, masociete LONGTEXT NOT NULL, monadresse LONGTEXT NOT NULL, montel LONGTEXT NOT NULL, nomclient LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, telclient LONGTEXT NOT NULL, datedevis DATE NOT NULL, totalht LONGTEXT NOT NULL, totaltva LONGTEXT NOT NULL, totalttc LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE formations (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, idemp LONGTEXT NOT NULL, datedebut DATE NOT NULL, fichier LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_commande_client (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_commande_fournisseur (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, prixunitaire LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixtotal LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_commande_fournisseur_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_devis (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_devis_clients_from_factures (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_devis_fournisseur (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, prixunitaire LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixtotal LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_devis_fournisseur_new (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_devisligne_facture_client_new_data (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_facture_client_new_data (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_facture_fournisseur_new_data (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_factures_clients (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_factures_fournisseurs (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, prixunitaire LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixtotal LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_factures_fournisseurss (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codedevis LONGTEXT NOT NULL, reference LONGTEXT NOT NULL, produit LONGTEXT NOT NULL, quantite LONGTEXT NOT NULL, prixdeventeht LONGTEXT NOT NULL, remise LONGTEXT NOT NULL, tva LONGTEXT NOT NULL, soustotalht LONGTEXT NOT NULL, soustotalttc LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE masociete (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, tel LONGTEXT NOT NULL, fax LONGTEXT NOT NULL, mobile LONGTEXT NOT NULL, codefinance LONGTEXT NOT NULL, codebancaire LONGTEXT NOT NULL, email LONGTEXT NOT NULL, website LONGTEXT NOT NULL, logo LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mouvement (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeproduit LONGTEXT NOT NULL, operation LONGTEXT NOT NULL, ancienvaleur LONGTEXT NOT NULL, nouvellevaleur LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation LONGTEXT NOT NULL, datemodification LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notedefrais (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeemp LONGTEXT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, fichier LONGTEXT NOT NULL, montant LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operation (id INT AUTO_INCREMENT NOT NULL, codeoperation LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, tempsexecution LONGTEXT NOT NULL, machine LONGTEXT NOT NULL, gamme LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ordre_de_fabrication (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeordre LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, priorite LONGTEXT NOT NULL, client LONGTEXT NOT NULL, commandeclient LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ordre_de_production (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, codeordre LONGTEXT NOT NULL, nom LONGTEXT NOT NULL, priorite LONGTEXT NOT NULL, client LONGTEXT NOT NULL, commandeclient LONGTEXT NOT NULL, etat LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recrutement (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, titre LONGTEXT NOT NULL, description LONGTEXT NOT NULL, idemp LONGTEXT NOT NULL, datedebut DATE NOT NULL, fichier LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, datemodification DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE secteur (id INT AUTO_INCREMENT NOT NULL, code INT NOT NULL, nom LONGTEXT NOT NULL, creepar LONGTEXT NOT NULL, datecreation DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE superheroes (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(70) NOT NULL, slug VARCHAR(70) NOT NULL, featured SMALLINT NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE agent_fournisseur');
        $this->addSql('DROP TABLE avoir_clients');
        $this->addSql('DROP TABLE avoir_clients_history');
        $this->addSql('DROP TABLE avoir_fournisseurs');
        $this->addSql('DROP TABLE commande_client');
        $this->addSql('DROP TABLE commande_fournisseur');
        $this->addSql('DROP TABLE commande_fournisseur_new');
        $this->addSql('DROP TABLE conge');
        $this->addSql('DROP TABLE contrat_client');
        $this->addSql('DROP TABLE contrat_fournisseur');
        $this->addSql('DROP TABLE devis');
        $this->addSql('DROP TABLE devis_fournisseur_new');
        $this->addSql('DROP TABLE devis_fournisseurs');
        $this->addSql('DROP TABLE deviserp_ligne_devis_fournisseurs_new');
        $this->addSql('DROP TABLE erp_absence');
        $this->addSql('DROP TABLE erp_admin');
        $this->addSql('DROP TABLE erp_bon_de_reception_fournisseur');
        $this->addSql('DROP TABLE erp_bon_livraison_client_new');
        $this->addSql('DROP TABLE erp_catalogue');
        $this->addSql('DROP TABLE erp_categorie_premiere');
        $this->addSql('DROP TABLE erp_chauffeurs');
        $this->addSql('DROP TABLE erp_client');
        $this->addSql('DROP TABLE erp_commande_client');
        $this->addSql('DROP TABLE erp_consomation_parc');
        $this->addSql('DROP TABLE erp_contact');
        $this->addSql('DROP TABLE erp_contact_categorie');
        $this->addSql('DROP TABLE erp_contrat_vehicule');
        $this->addSql('DROP TABLE erp_devis_client_new_from_factures');
        $this->addSql('DROP TABLE erp_devis_fournisseurs_new');
        $this->addSql('DROP TABLE erp_document');
        $this->addSql('DROP TABLE erp_ecriture_comptable');
        $this->addSql('DROP TABLE erp_employe');
        $this->addSql('DROP TABLE erp_equipe');
        $this->addSql('DROP TABLE erp_event');
        $this->addSql('DROP TABLE erp_factures_client');
        $this->addSql('DROP TABLE erp_factures_client_new');
        $this->addSql('DROP TABLE erp_factures_fournisseur_new');
        $this->addSql('DROP TABLE erp_factures_fournisseurs_new');
        $this->addSql('DROP TABLE erp_feuille_de_temps');
        $this->addSql('DROP TABLE erp_formation');
        $this->addSql('DROP TABLE erp_fournisseur');
        $this->addSql('DROP TABLE erp_heure_supp');
        $this->addSql('DROP TABLE erp_intervenant_categorie');
        $this->addSql('DROP TABLE erp_ligne_devis_fournisseurs_new');
        $this->addSql('DROP TABLE erp_ligne_factures_client');
        $this->addSql('DROP TABLE erp_ligne_factures_fournisseurs');
        $this->addSql('DROP TABLE erp_ligne_production');
        $this->addSql('DROP TABLE erp_location_parc');
        $this->addSql('DROP TABLE erp_matiere_premiere');
        $this->addSql('DROP TABLE erp_message');
        $this->addSql('DROP TABLE erp_modele_vehicule');
        $this->addSql('DROP TABLE erp_mouvement_stock');
        $this->addSql('DROP TABLE erp_note_de_frais');
        $this->addSql('DROP TABLE erp_notifications');
        $this->addSql('DROP TABLE erp_objectifs');
        $this->addSql('DROP TABLE erp_parametres');
        $this->addSql('DROP TABLE erp_pays');
        $this->addSql('DROP TABLE erp_pistes');
        $this->addSql('DROP TABLE erp_produit');
        $this->addSql('DROP TABLE erp_produit_compose');
        $this->addSql('DROP TABLE erp_projet');
        $this->addSql('DROP TABLE erp_releve_bancaire');
        $this->addSql('DROP TABLE erp_tache');
        $this->addSql('DROP TABLE erp_type_matiere_premiere');
        $this->addSql('DROP TABLE erp_vehicule');
        $this->addSql('DROP TABLE erp_ville');
        $this->addSql('DROP TABLE facture_autres_new_data');
        $this->addSql('DROP TABLE facture_client_new_data');
        $this->addSql('DROP TABLE facture_fournisseur_new_data');
        $this->addSql('DROP TABLE factures_clients');
        $this->addSql('DROP TABLE factures_fournisseurs');
        $this->addSql('DROP TABLE formations');
        $this->addSql('DROP TABLE ligne_commande_client');
        $this->addSql('DROP TABLE ligne_commande_fournisseur');
        $this->addSql('DROP TABLE ligne_commande_fournisseur_new');
        $this->addSql('DROP TABLE ligne_devis');
        $this->addSql('DROP TABLE ligne_devis_clients_from_factures');
        $this->addSql('DROP TABLE ligne_devis_fournisseur');
        $this->addSql('DROP TABLE ligne_devis_fournisseur_new');
        $this->addSql('DROP TABLE ligne_devisligne_facture_client_new_data');
        $this->addSql('DROP TABLE ligne_facture_client_new_data');
        $this->addSql('DROP TABLE ligne_facture_fournisseur_new_data');
        $this->addSql('DROP TABLE ligne_factures_clients');
        $this->addSql('DROP TABLE ligne_factures_fournisseurs');
        $this->addSql('DROP TABLE ligne_factures_fournisseurss');
        $this->addSql('DROP TABLE masociete');
        $this->addSql('DROP TABLE mouvement');
        $this->addSql('DROP TABLE notedefrais');
        $this->addSql('DROP TABLE operation');
        $this->addSql('DROP TABLE ordre_de_fabrication');
        $this->addSql('DROP TABLE ordre_de_production');
        $this->addSql('DROP TABLE recrutement');
        $this->addSql('DROP TABLE secteur');
        $this->addSql('DROP TABLE superheroes');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
